/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interface_grafica;

import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author User
 */
public class Erro extends javax.swing.JFrame {
    private Object janela;
    /**
     * Creates new form Erro
     */
    public Erro() {
        initComponents();
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE); //Desabilita o botão 'exit'
        this.setLocationRelativeTo(null); //INICIAR O JFRAME NO MEIO DA TELA
    }
    //AGEITAR IMAGEM
    public Erro(Object janela, String mensagem){
        this();
        this.janela = janela;
        this.lb_mensagem.setText(mensagem);
        this.lb_mensagem.setAlignmentY(CENTER_ALIGNMENT);
        if(janela != null){//Se for nulo, não é um JFrame
            JFrame jnl = new JFrame();
            jnl = (JFrame) janela;
            jnl.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb_titulo = new javax.swing.JLabel();
        lb_mensagem = new javax.swing.JLabel();
        btn_erro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lb_titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lb_titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/atencao.png"))); // NOI18N

        lb_mensagem.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lb_mensagem.setText("Mensagem");
        lb_mensagem.setAlignmentY(0.0F);
        lb_mensagem.setMaximumSize(new java.awt.Dimension(285, 16));

        btn_erro.setText("OK");
        btn_erro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_erroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_mensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(btn_erro)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_titulo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_mensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_erro)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_erroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_erroActionPerformed
        if(janela != null){//Se for nulo, não é um JFrame
            JFrame jnl = new JFrame();
            jnl = (JFrame) janela;
            jnl.setEnabled(true);
        }
        this.dispose();
    }//GEN-LAST:event_btn_erroActionPerformed

    public JLabel getLb_mensagem() {
        return lb_mensagem;
    }
    
    public JLabel getLb_titulo() {
        return lb_titulo;
    }

    public void setLb_titulo(String texto) {
        lb_titulo.setText(texto);
    }
    
    public void setLb_mensagem(String texto) {
        lb_mensagem.setText(texto);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Erro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Erro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Erro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Erro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Erro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_erro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_mensagem;
    private javax.swing.JLabel lb_titulo;
    // End of variables declaration//GEN-END:variables
}
