package interface_grafica;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author LT
 */
public class PreJogo extends javax.swing.JFrame {
    GUI_Principal gui;
    /**
     * Creates new form PreJogo
     */
    public PreJogo() {
        initComponents();
    }
    public PreJogo(GUI_Principal gui) {
        this();
        this.setLocationRelativeTo(null); //INICIAR O JFRAME NO MEIO DA TELA
        this.gui = gui;
        inicializaDados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_nome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jcb_modos = new javax.swing.JComboBox<>();
        jb_facil = new javax.swing.JRadioButton();
        jb_medio = new javax.swing.JRadioButton();
        jb_dificil = new javax.swing.JRadioButton();
        btn_jogar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Selecione o nível de dificuldade abaixo:");

        jLabel2.setText("Nome:");

        tf_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nomeActionPerformed(evt);
            }
        });

        jLabel3.setText("Selecione o modo de jogo:");

        jcb_modos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolher modo...", "Livre", "Carreira" }));
        jcb_modos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_modosActionPerformed(evt);
            }
        });

        jb_facil.setText("Fácil");
        jb_facil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_facilActionPerformed(evt);
            }
        });

        jb_medio.setText("Médio");
        jb_medio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_medioActionPerformed(evt);
            }
        });

        jb_dificil.setText("Difícil");
        jb_dificil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_dificilActionPerformed(evt);
            }
        });

        btn_jogar.setText("Jogar");
        btn_jogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_jogarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_jogar)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcb_modos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_medio)
                            .addComponent(jb_facil)
                            .addComponent(jb_dificil)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcb_modos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_facil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_medio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_dificil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_jogar)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nomeActionPerformed

    private void jb_facilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_facilActionPerformed
        if(jb_facil.isSelected()){
            jb_medio.setSelected(false);
            jb_dificil.setSelected(false);
        }
    }//GEN-LAST:event_jb_facilActionPerformed

    private void btn_jogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_jogarActionPerformed
        if(tf_nome.getText().length() < 1){
            new Erro(this,"Nome inválido").setVisible(true);
            tf_nome.requestFocus();
        }else if(jcb_modos.getSelectedIndex() < 1){
            new Erro(this,"Selecione um modo de jogo por favor").setVisible(true);
        }
        else if(!jb_facil.isSelected() && !jb_medio.isSelected() && !jb_dificil.isSelected() && jb_facil.isEnabled()){
            new Erro(this,"Selecione um nível por favor").setVisible(true);
        }else{
            gui.setVisible(true);
            gui.setEnabled(true);
            this.setEnabled(false);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btn_jogarActionPerformed

    private void jcb_modosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_modosActionPerformed
        jb_facil.setEnabled(true);
        jb_medio.setEnabled(true);
        jb_dificil.setEnabled(true);
        if(jcb_modos.getSelectedIndex() == 2){//Modo Carreira
            jb_facil.setEnabled(false);
            jb_medio.setEnabled(false);
            jb_dificil.setEnabled(false);
        }
    }//GEN-LAST:event_jcb_modosActionPerformed

    private void jb_medioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_medioActionPerformed
        if(jb_medio.isSelected()){
            jb_facil.setSelected(false);
            jb_dificil.setSelected(false);
        }
    }//GEN-LAST:event_jb_medioActionPerformed

    private void jb_dificilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_dificilActionPerformed
        if(jb_dificil.isSelected()){
            jb_medio.setSelected(false);
            jb_facil.setSelected(false);
        }
    }//GEN-LAST:event_jb_dificilActionPerformed
    
    public void inicializaDados(){
        tf_nome.setText("");
        jcb_modos.setSelectedIndex(0);
        jb_facil.setSelected(false);
        jb_medio.setSelected(false);
        jb_dificil.setSelected(false);
        tf_nome.requestFocus();
    }
    
    public JButton getBtn_jogar() {
        return btn_jogar;
    }
    
    public JComboBox<String> getJcb_modos() {
        return jcb_modos;
    }
    
    public JRadioButton getJb_dificil() {
        return jb_dificil;
    }

    public JRadioButton getJb_facil() {
        return jb_facil;
    }

    public JRadioButton getJb_medio() {
        return jb_medio;
    }

    public JTextField getTf_nome() {
        return tf_nome;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PreJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PreJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PreJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PreJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PreJogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_jogar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jb_dificil;
    private javax.swing.JRadioButton jb_facil;
    private javax.swing.JRadioButton jb_medio;
    private javax.swing.JComboBox<String> jcb_modos;
    private javax.swing.JTextField tf_nome;
    // End of variables declaration//GEN-END:variables
}
